/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.frontend;

import codeandbugs01.BaseDatos;
import java.awt.Color;
import java.awt.Dimension;
import java.text.ParseException;
import javax.swing.JOptionPane;
import project.backend.ManejadorDesktop;
import project.caso.frontend.CreadorTipoCaso;
import project.caso.frontend.RegistradorCaso;
import project.proyecto.frontend.CreadorProyecto;
import project.proyecto.frontend.ModificadorProyecto;
import project.usuario.frontend.*;

/**
 *
 * @author fabricio
 */
public class CodeAndBugsDescktop extends javax.swing.JFrame {

    ManejadorDesktop md = null;
    private BaseDatos DB = null;
    /**
     * Creates new form CodeAndBugsDescktop
     */
    public CodeAndBugsDescktop(int tipo, String nombreUsuario, BaseDatos DB) {
        initComponents();
        this.setLocationRelativeTo(null);
        md = new ManejadorDesktop();
        modificarItems(tipo, nombreUsuario);
        this.DB = DB;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrincipalDesktop = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        labelInformacion = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        jMenuAdminSistema = new javax.swing.JMenu();
        jMenuItemCrearUsuario = new javax.swing.JMenuItem();
        jMenuItemCrearProyecto = new javax.swing.JMenuItem();
        jMenuItemTipoCaso = new javax.swing.JMenuItem();
        jMenuAdminProy = new javax.swing.JMenu();
        jMenuItemRegCaso = new javax.swing.JMenuItem();
        jMenuDesarr = new javax.swing.JMenu();
        jMenuItemModificarProyecto = new javax.swing.JMenuItem();
        jMenuOpciones = new javax.swing.JMenu();
        jMenuItemCambiarUsuario = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Code 'n Bugs");

        PrincipalDesktop.setBackground(new java.awt.Color(254, 254, 254));

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        labelInformacion.setBackground(new java.awt.Color(254, 254, 254));
        labelInformacion.setFont(new java.awt.Font("Caviar Dreams", 1, 14)); // NOI18N
        labelInformacion.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(labelInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(labelInformacion)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menuBar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jMenuAdminSistema.setForeground(new java.awt.Color(254, 254, 254));
        jMenuAdminSistema.setText("Admin. Sistema");
        jMenuAdminSistema.setEnabled(false);

        jMenuItemCrearUsuario.setText("Crear/Registrar Usuario");
        jMenuItemCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearUsuarioActionPerformed(evt);
            }
        });
        jMenuAdminSistema.add(jMenuItemCrearUsuario);

        jMenuItemCrearProyecto.setText("Crear/Registrar Proyecto");
        jMenuItemCrearProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearProyectoActionPerformed(evt);
            }
        });
        jMenuAdminSistema.add(jMenuItemCrearProyecto);

        jMenuItemTipoCaso.setText("Crear/Registrar Tipo Caso");
        jMenuItemTipoCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTipoCasoActionPerformed(evt);
            }
        });
        jMenuAdminSistema.add(jMenuItemTipoCaso);

        menuBar.add(jMenuAdminSistema);

        jMenuAdminProy.setForeground(new java.awt.Color(254, 254, 254));
        jMenuAdminProy.setText("Admin. Proyecto");
        jMenuAdminProy.setEnabled(false);

        jMenuItemRegCaso.setText("Registrar caso");
        jMenuItemRegCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegCasoActionPerformed(evt);
            }
        });
        jMenuAdminProy.add(jMenuItemRegCaso);

        menuBar.add(jMenuAdminProy);

        jMenuDesarr.setForeground(new java.awt.Color(254, 254, 254));
        jMenuDesarr.setText("Desarrollador");
        jMenuDesarr.setEnabled(false);

        jMenuItemModificarProyecto.setText("Modificar Proyecto");
        jMenuItemModificarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModificarProyectoActionPerformed(evt);
            }
        });
        jMenuDesarr.add(jMenuItemModificarProyecto);

        menuBar.add(jMenuDesarr);

        jMenuOpciones.setForeground(new java.awt.Color(254, 254, 254));
        jMenuOpciones.setText("Opciones");

        jMenuItemCambiarUsuario.setText("Cambiar de Usuario");
        jMenuItemCambiarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCambiarUsuarioActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemCambiarUsuario);

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemSalir);

        menuBar.add(jMenuOpciones);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PrincipalDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1037, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PrincipalDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearUsuarioActionPerformed
        CreadorUsuario cu = new CreadorUsuario(this.DB);
        PrincipalDesktop.add(cu);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = cu.getSize();
        cu.setLocation((desktopSize.width - FrameSize.width) / 2, 0);
        cu.show();
    }//GEN-LAST:event_jMenuItemCrearUsuarioActionPerformed

    private void jMenuItemCambiarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCambiarUsuarioActionPerformed
        SolicitadorUsuario su = new SolicitadorUsuario(this, rootPaneCheckingEnabled, DB);
        this.dispose();
        su.setVisible(true);
    }//GEN-LAST:event_jMenuItemCambiarUsuarioActionPerformed

    private void jMenuItemCrearProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearProyectoActionPerformed
        CreadorProyecto cp = new CreadorProyecto(this.DB);
        PrincipalDesktop.add(cp);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = cp.getSize();
        cp.setLocation((desktopSize.width - FrameSize.width) / 2, 0);
        cp.show();
    }//GEN-LAST:event_jMenuItemCrearProyectoActionPerformed

    private void jMenuItemTipoCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTipoCasoActionPerformed
        CreadorTipoCaso ctc = new CreadorTipoCaso(this.DB);
        PrincipalDesktop.add(ctc);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = ctc.getSize();
        ctc.setLocation((desktopSize.width - FrameSize.width) / 2, 0);
        ctc.show();
    }//GEN-LAST:event_jMenuItemTipoCasoActionPerformed

    private void jMenuItemModificarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModificarProyectoActionPerformed
        ModificadorProyecto mp = new ModificadorProyecto(this.DB);
        PrincipalDesktop.add(mp);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = mp.getSize();
        mp.setLocation((desktopSize.width - FrameSize.width) / 2, 0);
        mp.show();
    }//GEN-LAST:event_jMenuItemModificarProyectoActionPerformed

    private void jMenuItemRegCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegCasoActionPerformed
        RegistradorCaso rc = new RegistradorCaso(this.DB);
        PrincipalDesktop.add(rc);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = rc.getSize();
        rc.setLocation((desktopSize.width - FrameSize.width) / 2, 0);
        rc.show();
    }//GEN-LAST:event_jMenuItemRegCasoActionPerformed

    /**
     * @param args the command line arguments
     */

    private void modificarItems(int tipo, String nombreUsuario){
        Color color = null;
        String tipoUsuario = " ";
        if(tipo == 1){
            color = new Color(246,145,1);
            tipoUsuario = "Administrador de Sistema";
            jMenuAdminSistema.setEnabled(true);
        } else if(tipo == 2){
            color = new Color(70, 130, 180);
            tipoUsuario = "Administrador de Proyecto";
            jMenuAdminProy.setEnabled(true);
        }
        menuBar.setBackground(color);
        labelInformacion.setText(nombreUsuario + " / " + tipoUsuario);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane PrincipalDesktop;
    private javax.swing.JMenu jMenuAdminProy;
    private javax.swing.JMenu jMenuAdminSistema;
    private javax.swing.JMenu jMenuDesarr;
    private javax.swing.JMenuItem jMenuItemCambiarUsuario;
    private javax.swing.JMenuItem jMenuItemCrearProyecto;
    private javax.swing.JMenuItem jMenuItemCrearUsuario;
    private javax.swing.JMenuItem jMenuItemModificarProyecto;
    private javax.swing.JMenuItem jMenuItemRegCaso;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemTipoCaso;
    private javax.swing.JMenu jMenuOpciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelInformacion;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
