/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.reportes.adminsistem;

import codeandbugs01.BaseDatos;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import project.caso.backend.HorasDinero;
import project.caso.backend.ManejadorCaso;
import project.caso.backend.TipoCaso;
import project.proyecto.backend.ManejadorProyecto;
import project.proyecto.backend.Proyecto;
import project.reportes.html.ExportadorHTML;
import project.reportes.html.ManejadorReportes;
import project.usuario.ManejadorUsuario;
import project.usuario.Usuario;

/**
 *
 * @author fabricio
 */
public class HorasDineroInvertido extends javax.swing.JInternalFrame {

    private BaseDatos DB = null; 
    private List<Proyecto> listaProyectos = null;
    private List<Usuario> listaUsuarios = null;
    private List<TipoCaso> listaTipoCasos = null;
    private HorasDinero hd1 = null;
    private HorasDinero hd2 = null;
    private HorasDinero hd3 = null;
    /**
     * Creates new form HorasDineroInvertido
     */
    public HorasDineroInvertido(BaseDatos DB) {
        this.DB = DB;
        this.listaProyectos = new LinkedList<>();
        this.listaUsuarios = new LinkedList<>();
        this.listaTipoCasos = new LinkedList<>();
        initComponents();
        actualizarProyectos();
        actualizarUsuarios();
        actualizarTipoCasos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buttonIdProy = new javax.swing.JButton();
        jComboBoxProy = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        textFieldHoras = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textFieldDinero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textFieldDinero1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        buttonDpiDesarr = new javax.swing.JButton();
        jComboBoxDpiDesr = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        textFieldHoras1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textFieldDinero2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        buttonTipoCaso = new javax.swing.JButton();
        jComboBoxTipoCaso = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        textFieldHoras2 = new javax.swing.JTextField();
        buttonIdProy1 = new javax.swing.JButton();
        buttonDpiDesarr1 = new javax.swing.JButton();
        buttonTipoCaso1 = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setBackground(new java.awt.Color(2, 161, 192));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(2, 161, 192));

        jLabel1.setFont(new java.awt.Font("Caviar Dreams", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Horas y Dinero Invertido");

        jSeparator1.setForeground(new java.awt.Color(254, 254, 254));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));

        buttonIdProy.setBackground(new java.awt.Color(246, 145, 1));
        buttonIdProy.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        buttonIdProy.setForeground(new java.awt.Color(254, 254, 254));
        buttonIdProy.setText("Mostrar");
        buttonIdProy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIdProyActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("ID Proyecto:");

        textFieldHoras.setEditable(false);
        textFieldHoras.setBackground(new java.awt.Color(2, 124, 139));
        textFieldHoras.setForeground(new java.awt.Color(254, 254, 254));
        textFieldHoras.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7));
        textFieldHoras.setCaretColor(new java.awt.Color(254, 254, 254));
        textFieldHoras.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Horas:");

        textFieldDinero.setEditable(false);
        textFieldDinero.setBackground(new java.awt.Color(2, 124, 139));
        textFieldDinero.setForeground(new java.awt.Color(254, 254, 254));
        textFieldDinero.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7));
        textFieldDinero.setCaretColor(new java.awt.Color(254, 254, 254));
        textFieldDinero.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Dinero:");

        textFieldDinero1.setEditable(false);
        textFieldDinero1.setBackground(new java.awt.Color(2, 124, 139));
        textFieldDinero1.setForeground(new java.awt.Color(254, 254, 254));
        textFieldDinero1.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7));
        textFieldDinero1.setCaretColor(new java.awt.Color(254, 254, 254));
        textFieldDinero1.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Dinero:");

        buttonDpiDesarr.setBackground(new java.awt.Color(246, 145, 1));
        buttonDpiDesarr.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        buttonDpiDesarr.setForeground(new java.awt.Color(254, 254, 254));
        buttonDpiDesarr.setText("Mostrar");
        buttonDpiDesarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDpiDesarrActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("DPI Desarrollador:");

        textFieldHoras1.setEditable(false);
        textFieldHoras1.setBackground(new java.awt.Color(2, 124, 139));
        textFieldHoras1.setForeground(new java.awt.Color(254, 254, 254));
        textFieldHoras1.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7));
        textFieldHoras1.setCaretColor(new java.awt.Color(254, 254, 254));
        textFieldHoras1.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setText("Horas:");

        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setText("Horas:");

        textFieldDinero2.setEditable(false);
        textFieldDinero2.setBackground(new java.awt.Color(2, 124, 139));
        textFieldDinero2.setForeground(new java.awt.Color(254, 254, 254));
        textFieldDinero2.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7));
        textFieldDinero2.setCaretColor(new java.awt.Color(254, 254, 254));
        textFieldDinero2.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jLabel10.setForeground(new java.awt.Color(254, 254, 254));
        jLabel10.setText("Dinero:");

        buttonTipoCaso.setBackground(new java.awt.Color(246, 145, 1));
        buttonTipoCaso.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        buttonTipoCaso.setForeground(new java.awt.Color(254, 254, 254));
        buttonTipoCaso.setText("Mostrar");
        buttonTipoCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTipoCasoActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(254, 254, 254));
        jLabel11.setText("Tipo de Caso:");

        textFieldHoras2.setEditable(false);
        textFieldHoras2.setBackground(new java.awt.Color(2, 124, 139));
        textFieldHoras2.setForeground(new java.awt.Color(254, 254, 254));
        textFieldHoras2.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7));
        textFieldHoras2.setCaretColor(new java.awt.Color(254, 254, 254));
        textFieldHoras2.setMargin(new java.awt.Insets(5, 5, 5, 5));

        buttonIdProy1.setBackground(new java.awt.Color(246, 145, 1));
        buttonIdProy1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        buttonIdProy1.setForeground(new java.awt.Color(254, 254, 254));
        buttonIdProy1.setText("Exportar HTML");
        buttonIdProy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIdProy1ActionPerformed(evt);
            }
        });

        buttonDpiDesarr1.setBackground(new java.awt.Color(246, 145, 1));
        buttonDpiDesarr1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        buttonDpiDesarr1.setForeground(new java.awt.Color(254, 254, 254));
        buttonDpiDesarr1.setText("Exportar HTML");
        buttonDpiDesarr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDpiDesarr1ActionPerformed(evt);
            }
        });

        buttonTipoCaso1.setBackground(new java.awt.Color(246, 145, 1));
        buttonTipoCaso1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        buttonTipoCaso1.setForeground(new java.awt.Color(254, 254, 254));
        buttonTipoCaso1.setText("Exportar HTML");
        buttonTipoCaso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTipoCaso1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1)
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldHoras1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldHoras2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonDpiDesarr1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonDpiDesarr, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonIdProy1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonIdProy, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonTipoCaso1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonTipoCaso, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(26, 26, 26)
                        .addComponent(textFieldDinero1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxProy, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26)
                        .addComponent(textFieldDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxDpiDesr, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(26, 26, 26)
                        .addComponent(textFieldDinero2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxTipoCaso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonIdProy)
                    .addComponent(jComboBoxProy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(buttonIdProy1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(textFieldDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDpiDesarr)
                    .addComponent(jComboBoxDpiDesr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(buttonDpiDesarr1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldHoras1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(textFieldDinero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTipoCaso)
                    .addComponent(jComboBoxTipoCaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(buttonTipoCaso1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldHoras2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(textFieldDinero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonIdProyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIdProyActionPerformed
        ManejadorCaso mc = new ManejadorCaso(DB);
        HorasDinero hd = mc.getHorasDineroByProyecto((String) jComboBoxProy.getSelectedItem());
        hd1 = hd;
        if(hd != null){
            textFieldHoras.setText(Double.toString(hd.getHorasInvertidas()));
            textFieldDinero.setText(Double.toString(hd.getDineroInvertido()));
        }
    }//GEN-LAST:event_buttonIdProyActionPerformed

    private void buttonDpiDesarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDpiDesarrActionPerformed
        ManejadorCaso mc = new ManejadorCaso(DB);
        HorasDinero hd = mc.getHorasDineroByDesarrollador((String)jComboBoxDpiDesr.getSelectedItem());
        hd2 = hd;
        if(hd != null){
            textFieldHoras1.setText(Double.toString(hd.getHorasInvertidas()));
            textFieldDinero1.setText(Double.toString(hd.getDineroInvertido()));
        }
    }//GEN-LAST:event_buttonDpiDesarrActionPerformed

    private void buttonTipoCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTipoCasoActionPerformed
        ManejadorCaso mc = new ManejadorCaso(DB);
        HorasDinero hd = mc.getHorasDineroByTipoCaso((String)jComboBoxTipoCaso.getSelectedItem());
        hd3 = hd;
        if(hd != null){
            textFieldHoras2.setText(Double.toString(hd.getHorasInvertidas()));
            textFieldDinero2.setText(Double.toString(hd.getDineroInvertido()));
        }
    }//GEN-LAST:event_buttonTipoCasoActionPerformed

    private void buttonIdProy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIdProy1ActionPerformed
        ExportadorHTML exportador = new ExportadorHTML(null, closable);
        ManejadorReportes mr = new ManejadorReportes();
        exportador.setVisible(true);
        mr.exportarHtmlHorasDineroInvertido(exportador.getFile(), hd1, "Proyecto");
        JOptionPane.showMessageDialog(rootPane, "Se ha guardado exitosamente el archivo HTML deseado", "Accion exitosa", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonIdProy1ActionPerformed

    private void buttonDpiDesarr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDpiDesarr1ActionPerformed
        ExportadorHTML exportador = new ExportadorHTML(null, closable);
        ManejadorReportes mr = new ManejadorReportes();
        exportador.setVisible(true);
        mr.exportarHtmlHorasDineroInvertido(exportador.getFile(), hd2, "Desarrollador");
        JOptionPane.showMessageDialog(rootPane, "Se ha guardado exitosamente el archivo HTML deseado", "Accion exitosa", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonDpiDesarr1ActionPerformed

    private void buttonTipoCaso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTipoCaso1ActionPerformed
        ExportadorHTML exportador = new ExportadorHTML(null, closable);
        ManejadorReportes mr = new ManejadorReportes();
        exportador.setVisible(true);
        mr.exportarHtmlHorasDineroInvertido(exportador.getFile(), hd3, "Tipo de Caso");
        JOptionPane.showMessageDialog(rootPane, "Se ha guardado exitosamente el archivo HTML deseado", "Accion exitosa", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonTipoCaso1ActionPerformed

    private void actualizarProyectos(){
        ManejadorProyecto mp = new ManejadorProyecto(DB);
        this.listaProyectos.clear();
        if(mp.getProyectos() != null){
            listaProyectos.addAll(mp.getProyectos());
            for (Proyecto proyecto : listaProyectos) {
                jComboBoxProy.addItem(Integer.toString(proyecto.getID()));
            }
        }
    }

    private void actualizarUsuarios(){
        ManejadorUsuario mu = new ManejadorUsuario(DB);
        this.listaUsuarios.clear();
        if(mu.getUsuarioByTipo("3") != null){
            this.listaUsuarios.addAll(mu.getUsuarioByTipo("3"));
            for (Usuario usr : listaUsuarios) {
                jComboBoxDpiDesr.addItem(Integer.toString(usr.getDPI()));
            }
        }
    }
    
    private void actualizarTipoCasos(){
        ManejadorCaso mc = new ManejadorCaso(DB);
        this.listaTipoCasos.clear();
        if(mc.getTipoCaso() != null){
            this.listaTipoCasos.addAll(mc.getTipoCaso());
            for (TipoCaso tipoCaso : listaTipoCasos) {
                jComboBoxTipoCaso.addItem(tipoCaso.getNombre());
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDpiDesarr;
    private javax.swing.JButton buttonDpiDesarr1;
    private javax.swing.JButton buttonIdProy;
    private javax.swing.JButton buttonIdProy1;
    private javax.swing.JButton buttonTipoCaso;
    private javax.swing.JButton buttonTipoCaso1;
    private javax.swing.JComboBox<String> jComboBoxDpiDesr;
    private javax.swing.JComboBox<String> jComboBoxProy;
    private javax.swing.JComboBox<String> jComboBoxTipoCaso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField textFieldDinero;
    private javax.swing.JTextField textFieldDinero1;
    private javax.swing.JTextField textFieldDinero2;
    private javax.swing.JTextField textFieldHoras;
    private javax.swing.JTextField textFieldHoras1;
    private javax.swing.JTextField textFieldHoras2;
    // End of variables declaration//GEN-END:variables
}
