package project.reportes.adminsistem;

import codeandbugs01.BaseDatos;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import project.caso.backend.CantidadCasos;
import project.caso.backend.ManejadorCaso;
import project.reportes.html.ExportadorHTML;
import project.reportes.html.ManejadorReportes;


/**
 *
 * @author fabricio
 */
public class MostradorCantidadCasos extends javax.swing.JInternalFrame {

    private BaseDatos DB = null;
    private List<CantidadCasos> listaCasos = null;
    private ObservableList<CantidadCasos> listaCasosObsr = null;
    /**
     * Creates new form CantidadCasos
     */
    public MostradorCantidadCasos(BaseDatos DB) {
        this.DB = DB;
        this.listaCasos = new LinkedList<>();
        this.listaCasosObsr = ObservableCollections.observableList(listaCasos);
        initComponents();
        actualizarCasos(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonTodo = new javax.swing.JButton();
        buttonInactivos = new javax.swing.JButton();
        buttonActivo = new javax.swing.JButton();
        buttonTodo1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(2, 161, 192));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(2, 161, 192));

        jLabel1.setFont(new java.awt.Font("Caviar Dreams", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Cantidad de Casos");

        jSeparator1.setForeground(new java.awt.Color(254, 254, 254));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${listaCasosObsr}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idProyecto}"));
        columnBinding.setColumnName("ID Proyecto");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nombreProyecto}"));
        columnBinding.setColumnName("Nombre Proyecto");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cantidadCasos}"));
        columnBinding.setColumnName("Cantidad Casos");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${estado}"));
        columnBinding.setColumnName("Estado");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);

        buttonTodo.setBackground(new java.awt.Color(246, 145, 1));
        buttonTodo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        buttonTodo.setForeground(new java.awt.Color(254, 254, 254));
        buttonTodo.setText("Mostrar Todos");
        buttonTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTodoActionPerformed(evt);
            }
        });

        buttonInactivos.setBackground(new java.awt.Color(246, 145, 1));
        buttonInactivos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        buttonInactivos.setForeground(new java.awt.Color(254, 254, 254));
        buttonInactivos.setText("Inactivos");
        buttonInactivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInactivosActionPerformed(evt);
            }
        });

        buttonActivo.setBackground(new java.awt.Color(246, 145, 1));
        buttonActivo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        buttonActivo.setForeground(new java.awt.Color(254, 254, 254));
        buttonActivo.setText("Activos");
        buttonActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActivoActionPerformed(evt);
            }
        });

        buttonTodo1.setBackground(new java.awt.Color(246, 145, 1));
        buttonTodo1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        buttonTodo1.setForeground(new java.awt.Color(254, 254, 254));
        buttonTodo1.setText("Exportar a HTML");
        buttonTodo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTodo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(buttonActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(buttonTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(buttonInactivos, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(buttonTodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTodo)
                    .addComponent(buttonInactivos)
                    .addComponent(buttonActivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(buttonTodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTodoActionPerformed
        actualizarCasos(2);
    }//GEN-LAST:event_buttonTodoActionPerformed

    private void buttonInactivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInactivosActionPerformed
        actualizarCasos(0);
    }//GEN-LAST:event_buttonInactivosActionPerformed

    private void buttonActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActivoActionPerformed
        actualizarCasos(1);
    }//GEN-LAST:event_buttonActivoActionPerformed

    private void buttonTodo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTodo1ActionPerformed
        ExportadorHTML exportador = new ExportadorHTML(null, closable);
        ManejadorReportes mr = new ManejadorReportes();
        exportador.setVisible(true);
        mr.exportarHtmlCantidadCasos(exportador.getFile(), listaCasosObsr);
        JOptionPane.showMessageDialog(rootPane, "Se ha guardado exitosamente el archivo HTML deseado", "Accion exitosa", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonTodo1ActionPerformed

    private void actualizarCasos(int status){
        ManejadorCaso mc = new ManejadorCaso(DB);
        this.listaCasosObsr.clear();
        if(mc.getCantidadCasosAndStatus(status) != null){
            this.listaCasosObsr.addAll(mc.getCantidadCasosAndStatus(status));
        }
    }
    
    public ObservableList<CantidadCasos> getListaCasosObsr() {
        return listaCasosObsr;
    }

    public void setListaCasosObsr(ObservableList<CantidadCasos> listaCasosObsr) {
        this.listaCasosObsr = listaCasosObsr;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonActivo;
    private javax.swing.JButton buttonInactivos;
    private javax.swing.JButton buttonTodo;
    private javax.swing.JButton buttonTodo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
