/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.reportes.adminsistem;

import codeandbugs01.BaseDatos;
import project.caso.backend.ManejadorCaso;
import project.proyecto.backend.ManejadorProyecto;

/**
 *
 * @author fabricio
 */
public class ReporteProyecto extends javax.swing.JInternalFrame {

    private BaseDatos DB = null;
    
    /**
     * Creates new form ReporteProyecto
     */
    public ReporteProyecto(BaseDatos DB) {
        this.DB = DB;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        buttonTipoCaso = new javax.swing.JButton();
        textFieldDpiAdmin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textFieldIDProy = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textFieldNombreProy = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textFieldIDProy1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textFieldNombreProy1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textFieldDpiAdmin1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(2, 161, 192));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setBackground(new java.awt.Color(2, 161, 192));

        jLabel1.setFont(new java.awt.Font("Caviar Dreams", 0, 34)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Proyecto con mas casos finalizados");

        jSeparator1.setForeground(new java.awt.Color(254, 254, 254));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));

        jLabel2.setFont(new java.awt.Font("Caviar Dreams", 0, 34)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Proyecto con mas casos cancelados");

        jSeparator2.setForeground(new java.awt.Color(254, 254, 254));
        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 5));

        buttonTipoCaso.setBackground(new java.awt.Color(246, 145, 1));
        buttonTipoCaso.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        buttonTipoCaso.setForeground(new java.awt.Color(254, 254, 254));
        buttonTipoCaso.setText("Actualizar");
        buttonTipoCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTipoCasoActionPerformed(evt);
            }
        });

        textFieldDpiAdmin.setEditable(false);
        textFieldDpiAdmin.setBackground(new java.awt.Color(2, 124, 139));
        textFieldDpiAdmin.setForeground(new java.awt.Color(254, 254, 254));
        textFieldDpiAdmin.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7));
        textFieldDpiAdmin.setCaretColor(new java.awt.Color(254, 254, 254));
        textFieldDpiAdmin.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("DPI Administrador");

        textFieldIDProy.setEditable(false);
        textFieldIDProy.setBackground(new java.awt.Color(2, 124, 139));
        textFieldIDProy.setForeground(new java.awt.Color(254, 254, 254));
        textFieldIDProy.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7));
        textFieldIDProy.setCaretColor(new java.awt.Color(254, 254, 254));
        textFieldIDProy.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("ID:");

        textFieldNombreProy.setEditable(false);
        textFieldNombreProy.setBackground(new java.awt.Color(2, 124, 139));
        textFieldNombreProy.setForeground(new java.awt.Color(254, 254, 254));
        textFieldNombreProy.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7));
        textFieldNombreProy.setCaretColor(new java.awt.Color(254, 254, 254));
        textFieldNombreProy.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Nombre:");

        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("DPI Administrador");

        textFieldIDProy1.setEditable(false);
        textFieldIDProy1.setBackground(new java.awt.Color(2, 124, 139));
        textFieldIDProy1.setForeground(new java.awt.Color(254, 254, 254));
        textFieldIDProy1.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7));
        textFieldIDProy1.setCaretColor(new java.awt.Color(254, 254, 254));
        textFieldIDProy1.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setText("ID:");

        textFieldNombreProy1.setEditable(false);
        textFieldNombreProy1.setBackground(new java.awt.Color(2, 124, 139));
        textFieldNombreProy1.setForeground(new java.awt.Color(254, 254, 254));
        textFieldNombreProy1.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7));
        textFieldNombreProy1.setCaretColor(new java.awt.Color(254, 254, 254));
        textFieldNombreProy1.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setText("Nombre:");

        textFieldDpiAdmin1.setEditable(false);
        textFieldDpiAdmin1.setBackground(new java.awt.Color(2, 124, 139));
        textFieldDpiAdmin1.setForeground(new java.awt.Color(254, 254, 254));
        textFieldDpiAdmin1.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7));
        textFieldDpiAdmin1.setCaretColor(new java.awt.Color(254, 254, 254));
        textFieldDpiAdmin1.setMargin(new java.awt.Insets(5, 5, 5, 5));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(textFieldIDProy1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(textFieldNombreProy1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(textFieldDpiAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(buttonTipoCaso, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(textFieldIDProy, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(textFieldNombreProy, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(textFieldDpiAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(9, 9, 9)
                        .addComponent(textFieldIDProy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(9, 9, 9)
                        .addComponent(textFieldNombreProy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(9, 9, 9)
                        .addComponent(textFieldDpiAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(9, 9, 9)
                        .addComponent(textFieldIDProy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(9, 9, 9)
                        .addComponent(textFieldNombreProy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(9, 9, 9)
                        .addComponent(textFieldDpiAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(buttonTipoCaso)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTipoCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTipoCasoActionPerformed
//        ManejadorProyecto mp = new ManejadorProyecto(DB);
//        ManejadorCaso mc = new ManejadorCaso(DB);
//        System.out.println(mc.getNumeroFinalizado("1"));
    }//GEN-LAST:event_buttonTipoCasoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonTipoCaso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField textFieldDpiAdmin;
    private javax.swing.JTextField textFieldDpiAdmin1;
    private javax.swing.JTextField textFieldIDProy;
    private javax.swing.JTextField textFieldIDProy1;
    private javax.swing.JTextField textFieldNombreProy;
    private javax.swing.JTextField textFieldNombreProy1;
    // End of variables declaration//GEN-END:variables
}
