/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.etapa.frontend;

import codeandbugs01.BaseDatos;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import project.caso.backend.ManejadorCaso;
import project.etapa.backend.Etapa;
import project.etapa.backend.ManejadorEtapa;
import project.usuario.Usuario;

/**
 *
 * @author fabricio
 */
public class AprobadorTrabajo extends javax.swing.JInternalFrame {

    private BaseDatos DB = null;
    private List<Etapa> listaEtapas = null;
    private ObservableList<Etapa> listaEtapasObs = null;
    private Etapa etapaSelecc = null;
    private Usuario usuario = null;
    
    public AprobadorTrabajo(BaseDatos DB, Usuario usuario) {
        this.DB = DB;
        this.listaEtapas = new LinkedList<>();
        this.listaEtapasObs = ObservableCollections.observableList(listaEtapas);
        this.etapaSelecc = new Etapa(0, 0, null, 0, new Byte("0"), 0,0);
        this.usuario = usuario;
        initComponents();
        estadoBotones(false);
        actualizarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonAprobar = new javax.swing.JButton();
        buttonRechazar = new javax.swing.JButton();
        formattedTextFieldFecha = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 99, 71));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setClosable(true);
        setTitle("Aprobar Trabajo");

        jPanel1.setBackground(new java.awt.Color(255, 99, 71));

        jLabel1.setFont(new java.awt.Font("Caviar Dreams", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Aprobar Trabajo");

        jSeparator1.setForeground(new java.awt.Color(254, 254, 254));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${listaEtapasObs}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${numeroPaso}"));
        columnBinding.setColumnName("Numero Paso");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idCaso}"));
        columnBinding.setColumnName("Id Caso");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${comentario}"));
        columnBinding.setColumnName("Comentario");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dpiDesarrollador}"));
        columnBinding.setColumnName("Dpi Desarrollador");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${etapaSelecc}"), jTable1, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        buttonAprobar.setBackground(new java.awt.Color(70, 130, 180));
        buttonAprobar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        buttonAprobar.setForeground(new java.awt.Color(254, 254, 254));
        buttonAprobar.setText("Aprobar");
        buttonAprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAprobarActionPerformed(evt);
            }
        });

        buttonRechazar.setBackground(new java.awt.Color(254, 254, 254));
        buttonRechazar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        buttonRechazar.setForeground(new java.awt.Color(254, 51, 51));
        buttonRechazar.setText("Rechazar");
        buttonRechazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRechazarActionPerformed(evt);
            }
        });

        formattedTextFieldFecha.setBackground(new java.awt.Color(254, 254, 254));
        formattedTextFieldFecha.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7));
        formattedTextFieldFecha.setForeground(new java.awt.Color(237, 71, 71));
        try {
            formattedTextFieldFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formattedTextFieldFecha.setCaretColor(new java.awt.Color(237, 71, 71));

        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Fecha:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(156, 156, 156))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonAprobar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formattedTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonRechazar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonAprobar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(formattedTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonRechazar)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAprobarActionPerformed
        ManejadorEtapa me = new ManejadorEtapa(DB);
        ManejadorCaso mc = new ManejadorCaso(DB);
        try {
            me.aprobarEtapa(etapaSelecc);
            mc.updateCasoDateAvance(etapaSelecc, formattedTextFieldFecha.getText());
            JOptionPane.showMessageDialog(rootPane, "Se ha aprobado exitosamente el trabajo seleccionado", "Accion exitosa", JOptionPane.INFORMATION_MESSAGE);
            actualizarLista();
        } catch (Exception e) {
            e.printStackTrace(System.out);
        }
        estadoBotones(false);
    }//GEN-LAST:event_buttonAprobarActionPerformed

    private void buttonRechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRechazarActionPerformed
        ManejadorEtapa me = new ManejadorEtapa(DB);
        try {
            me.rechazarEtapa(etapaSelecc);
            JOptionPane.showMessageDialog(rootPane, "Se ha rechazado el trabajo exitosamente", "Accion exitosa", JOptionPane.INFORMATION_MESSAGE);
            actualizarLista();
        } catch (Exception e) {
            e.printStackTrace(System.out);
        }
        estadoBotones(false);
    }//GEN-LAST:event_buttonRechazarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        estadoBotones(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void estadoBotones(boolean estado){
        buttonAprobar.setEnabled(estado);
        buttonRechazar.setEnabled(estado);
    }
    
    private void actualizarLista(){
        ManejadorEtapa me = new ManejadorEtapa(DB);
        listaEtapasObs.clear();
        if(me.getEtapaComentarioNotNull(usuario) != null){
            listaEtapasObs.addAll(me.getEtapaComentarioNotNull(usuario));
        }
    }

    public ObservableList<Etapa> getListaEtapasObs() {
        return listaEtapasObs;
    }

    public void setListaEtapasObs(ObservableList<Etapa> listaEtapasObs) {
        this.listaEtapasObs = listaEtapasObs;
    }

    public Etapa getEtapaSelecc() {
        return etapaSelecc;
    }

    public void setEtapaSelecc(Etapa etapaSelecc) {
        this.etapaSelecc = etapaSelecc;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAprobar;
    private javax.swing.JButton buttonRechazar;
    private javax.swing.JFormattedTextField formattedTextFieldFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
