/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.etapa.frontend;

import codeandbugs01.BaseDatos;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import project.caso.backend.Caso;
import project.caso.backend.ManejadorCaso;
import project.caso.backend.TipoCaso;
import project.etapa.backend.ManejadorEtapa;
import project.usuario.ManejadorUsuario;
import project.usuario.Usuario;

/**
 *
 * @author fabricio
 */
public class RegistradorEtapa extends javax.swing.JInternalFrame {

    private BaseDatos DB = null;
    private Usuario usr = null;
    private List<Caso> listaCasos = null;
    private TipoCaso tipoCaso = null;

    public RegistradorEtapa(BaseDatos DB, Usuario usr) {
        initComponents();
        this.DB = DB;
        this.usr = usr;
        this.listaCasos = new LinkedList<>();
        actualizarListas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxIDCaso = new javax.swing.JComboBox<>();
        buttonRegistrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 99, 71));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setClosable(true);
        setTitle("Registrador Etapa");
        setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(255, 99, 71));

        jLabel1.setFont(new java.awt.Font("Caviar Dreams", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Registrar Etapas");

        jSeparator1.setForeground(new java.awt.Color(254, 254, 254));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));

        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("ID Caso*:");

        jComboBoxIDCaso.setBackground(new java.awt.Color(254, 254, 254));
        jComboBoxIDCaso.setForeground(new java.awt.Color(237, 71, 71));
        jComboBoxIDCaso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBoxIDCasoMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxIDCasoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBoxIDCasoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxIDCasoMouseEntered(evt);
            }
        });
        jComboBoxIDCaso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxIDCasoKeyPressed(evt);
            }
        });

        buttonRegistrar.setBackground(new java.awt.Color(70, 130, 180));
        buttonRegistrar.setFont(new java.awt.Font("Caviar Dreams", 0, 24)); // NOI18N
        buttonRegistrar.setForeground(new java.awt.Color(254, 254, 254));
        buttonRegistrar.setText("Registrar");
        buttonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Seleccione el ID Caso que desea utilizar para registrar las etapas necesarias");

        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("y posteriormente colocar a su respectivo Desarrollador.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(jLabel4))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(buttonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxIDCaso, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxIDCaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addComponent(buttonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarActionPerformed
        ManejadorCaso mc = new ManejadorCaso(this.DB);
        ManejadorEtapa me = new ManejadorEtapa(this.DB);
        String itemSelecc = (String) jComboBoxIDCaso.getSelectedItem();
        if (itemSelecc.replaceAll(" ", "").isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "No cuenta con casos asignados, intentelo en otra oportunidad");
        } else {
            this.tipoCaso = mc.getTipoCasoByCasoId(itemSelecc);
            if (me.getEtapaByCasoAndPaso("1", itemSelecc) == null) {
                try {
                    me.setEtapaNoPasoIdCaso(tipoCaso.getNumeroPasos(), itemSelecc);
                    JOptionPane.showMessageDialog(rootPane, "Se han registrado exitosamente las etapas del Caso \""
                            + itemSelecc + "\"", "Accion exitosa", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Error de validacion", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "No es posible registrar las etapas, pues ya han sido creadas anteriormente",
                        "Error de validacion", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_buttonRegistrarActionPerformed

    private void jComboBoxIDCasoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxIDCasoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxIDCasoMouseClicked

    private void jComboBoxIDCasoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxIDCasoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxIDCasoKeyPressed

    private void jComboBoxIDCasoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxIDCasoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxIDCasoMouseEntered

    private void jComboBoxIDCasoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxIDCasoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxIDCasoMousePressed

    private void jComboBoxIDCasoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxIDCasoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxIDCasoMouseExited

    private void actualizarListas() {
        ManejadorCaso mc = new ManejadorCaso(this.DB);
        listaCasos.clear();
        if (mc.getCasoByStatusAndDpiAdmin(this.usr) != null) {
            listaCasos.addAll(mc.getCasoByStatusAndDpiAdmin(this.usr));
            for (Caso caso : listaCasos) {
                jComboBoxIDCaso.addItem(Integer.toString(caso.getID()));
            }
        } else {
            jComboBoxIDCaso.addItem("");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRegistrar;
    private javax.swing.JComboBox<String> jComboBoxIDCaso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
